# YOUR NAME OR TITLE OF YOUR SITE
name: The Reading Globe

# YOUR BRAND/PERSONAL TAGLINE
tagline: Your go-to source for trending books üìö and reviews ‚úçto fuel your literary journey.

# YOUR/BRAND IMAGE URL
Image_URL: https://github.com/thereadingglobe/links/blob/main/logo.jpg

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://picsum.photos/1080?nocache=

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
       # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com/
    Username: thereadingglobe
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram

 

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
# footer: 'Yes'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
