# YOUR NAME OR TITLE OF YOUR SITE
name: The Reading Globe

# YOUR BRAND/PERSONAL TAGLINE
tagline: Your go-to source for trending books üìö and reviews ‚úçto fuel your literary journey.

# YOUR/BRAND IMAGE URL
Image_URL: https://thereadingglobe.github.io/links/logo.jpg

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://picsum.photos/1080?nocache=

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
       # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com/thereadingglobe
    Username: ''
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram
  
- Name: The Science Book Big Ideas Simply Explained
    URL: https://www.amazon.sg/Science-Book-Ideas-Simply-Explained/dp/1465481222/ref=sr_1_1?tag=thereadingglo-22
    Username: ''
    Color: '#43FD79'
    Icon-Class: fas fa-book

  - Name: The Science Book Everything You Need to Know ab...
    URL: https://www.amazon.sg/Science-Book-Everything-about-World/dp/1426208081/ref=sr_1_2?tag=thereadingglo-22
    Username: ''
    Color: '#8D8935'
    Icon-Class: fas fa-book

  - Name: Outlive The Science and Art of Longevity
    URL: https://www.amazon.sg/Outlive-Longevity-Peter-Attia-MD/dp/0593236599/ref=sr_1_3?tag=thereadingglo-22
    Username: ''
    Color: '#71E699'
    Icon-Class: fas fa-book

  - Name: Science!
    URL: https://www.amazon.sg/Science-DK/dp/1465473637/ref=sr_1_4?tag=thereadingglo-22
    Username: ''
    Color: '#4913AD'
    Icon-Class: fas fa-book

  - Name: The Song of the Cell An Exploration of Medicine...
    URL: https://www.amazon.sg/Song-Cell-Exploration-Medicine-Human/dp/1847925979/ref=sr_1_5?tag=thereadingglo-22
    Username: ''
    Color: '#099408'
    Icon-Class: fas fa-book

  - Name: Science Encyclopedia Atom Smashing, Food Chemis...
    URL: https://www.amazon.sg/Science-Encyclopedia-Smashing-Chemistry-Animals/dp/1426325428/ref=sr_1_6?tag=thereadingglo-22
    Username: ''
    Color: '#E65FDB'
    Icon-Class: fas fa-book

  - Name: The Biggest Ideas in the Universe Space, Time, ...
    URL: https://www.amazon.sg/Biggest-Ideas-Universe-Space-Motion/dp/0593186583/ref=sr_1_7?tag=thereadingglo-22
    Username: ''
    Color: '#C7C6E2'
    Icon-Class: fas fa-book

  - Name: The Fascinating Science Book for Kids 500 Amazi...
    URL: https://www.amazon.sg/Fascinating-Science-Book-Kids-Amazing/dp/1647398703/ref=sr_1_8?tag=thereadingglo-22
    Username: ''
    Color: '#EF0788'
    Icon-Class: fas fa-book

  - Name: The Elements Book A Visual Encyclopedia of the ...
    URL: https://www.amazon.sg/Elements-Book-Visual-Encyclopedia-Periodic/dp/1465456600/ref=sr_1_9?tag=thereadingglo-22
    Username: ''
    Color: '#212A6F'
    Icon-Class: fas fa-book

  - Name: Behave The Biology of Humans at Our Best and Worst
    URL: https://www.amazon.sg/Behave-Biology-Humans-Best-Worst/dp/0143110918/ref=sr_1_10?tag=thereadingglo-22
    Username: ''
    Color: '#2D6F3D'
    Icon-Class: fas fa-book

  - Name: Everything You Need to Ace Science in One Big F...
    URL: https://www.amazon.sg/Everything-You-Need-Science-Notebook/dp/0761160957/ref=sr_1_11?tag=thereadingglo-22
    Username: ''
    Color: '#1D6BEB'
    Icon-Class: fas fa-book

  - Name: Berenstain Bears Big Book of Science and Nature
    URL: https://www.amazon.sg/Berenstain-Bears-Book-Science-Nature/dp/0486498344/ref=sr_1_12?tag=thereadingglo-22
    Username: ''
    Color: '#F2472C'
    Icon-Class: fas fa-book

  - Name: The Science of Spice Understand Flavor Connecti...
    URL: https://www.amazon.sg/Science-Spice-Understand-Connections-Revolutionize/dp/1465475575/ref=sr_1_13?tag=thereadingglo-22
    Username: ''
    Color: '#B481ED'
    Icon-Class: fas fa-book

  - Name: Interesting Facts For Curious Minds 1572 Random...
    URL: https://www.amazon.sg/Interesting-Facts-Curious-Minds-Mind-Blowing/dp/B0B6XFT4RH/ref=sr_1_14?tag=thereadingglo-22
    Username: ''
    Color: '#51FF17'
    Icon-Class: fas fa-book

  - Name: Immune A Journey Into the Mysterious System Tha...
    URL: https://www.amazon.sg/Immune-Journey-Mysterious-System-Keeps/dp/0593241312/ref=sr_1_15?tag=thereadingglo-22
    Username: ''
    Color: '#D2AEBE'
    Icon-Class: fas fa-book

  - Name: The Code Book The Science of Secrecy from Ancie...
    URL: https://www.amazon.sg/Code-Book-Science-Secrecy-Cryptography/dp/0385495323/ref=sr_1_16?tag=thereadingglo-22
    Username: ''
    Color: '#CCF322'
    Icon-Class: fas fa-book

  - Name: 5,000 Awesome Facts (about Everything!)
    URL: https://www.amazon.sg/000-Awesome-Facts-about-Everything/dp/1426310498/ref=sr_1_17?tag=thereadingglo-22
    Username: ''
    Color: '#A2CD67'
    Icon-Class: fas fa-book

  - Name: Universe, Third Edition The Definitive Visual G...
    URL: https://www.amazon.sg/Universe-Third-Definitive-Visual-Guide/dp/1465499954/ref=sr_1_18?tag=thereadingglo-22
    Username: ''
    Color: '#31491A'
    Icon-Class: fas fa-book

  - Name: The Art of Doing Science and Engineering Learni...
    URL: https://www.amazon.sg/Art-Doing-Science-Engineering-Learning/dp/1732265178/ref=sr_1_19?tag=thereadingglo-22
    Username: ''
    Color: '#B06E24'
    Icon-Class: fas fa-book

  - Name: Awesome Science Experiments for Kids 100+ Fun S...
    URL: https://www.amazon.sg/Awesome-Science-Experiments-Kids-Projects/dp/1939754666/ref=sr_1_20?tag=thereadingglo-22
    Username: ''
    Color: '#141D36'
    Icon-Class: fas fa-book

  - Name: The Food Lab Better Home Cooking Through Science
    URL: https://www.amazon.sg/Food-Lab-Cooking-Through-Science/dp/0393081087/ref=sr_1_21?tag=thereadingglo-22
    Username: ''
    Color: '#2E61D0'
    Icon-Class: fas fa-book

  - Name: The Book of Why The New Science of Cause and Ef...
    URL: https://www.amazon.sg/Book-Why-Science-Cause-Effect/dp/1541698967/ref=sr_1_22?tag=thereadingglo-22
    Username: ''
    Color: '#C79D78'
    Icon-Class: fas fa-book

  - Name: What If? Serious Scientific Answers to Absurd H...
    URL: https://www.amazon.sg/What-If-Scientific-Hypothetical-Questions/dp/0544272994/ref=sr_1_23?tag=thereadingglo-22
    Username: ''
    Color: '#13B43B'
    Icon-Class: fas fa-book

  - Name: How to Be Good at Science, Technology, and Engi...
    URL: https://www.amazon.sg/How-Good-Science-Technology-Engineering/dp/0241227860/ref=sr_1_24?tag=thereadingglo-22
    Username: ''
    Color: '#16B0E3'
    Icon-Class: fas fa-book

  - Name: How To Absurd Scientific Advice for Common Real...
    URL: https://www.amazon.sg/How-Absurd-Scientific-Real-World-Problems/dp/0525537090/ref=sr_1_25?tag=thereadingglo-22
    Username: ''
    Color: '#86F9F9'
    Icon-Class: fas fa-book

  - Name: Chaos Making a New Science
    URL: https://www.amazon.sg/Chaos-Making-Science-James-Gleick/dp/0143113453/ref=sr_1_26?tag=thereadingglo-22
    Username: ''
    Color: '#4B803F'
    Icon-Class: fas fa-book

  - Name: Women In Science 50 Fearless Pioneers Who Chang...
    URL: https://www.amazon.sg/Women-Science-Fearless-Pioneers-Changed/dp/1607749769/ref=sr_1_27?tag=thereadingglo-22
    Username: ''
    Color: '#225014'
    Icon-Class: fas fa-book

  - Name: Algorithms to Live by The Computer Science of H...
    URL: https://www.amazon.sg/Algorithms-Live-Computer-Science-Decisions/dp/1250118360/ref=sr_1_28?tag=thereadingglo-22
    Username: ''
    Color: '#2DFB56'
    Icon-Class: fas fa-book

  - Name: National Geographic Science of Everything How T...
    URL: https://www.amazon.sg/National-Geographic-Science-Everything-Things/dp/1426211686/ref=sr_1_29?tag=thereadingglo-22
    Username: ''
    Color: '#AEBDDF'
    Icon-Class: fas fa-book

  - Name: The Physics Book Big Ideas Simply Explained
    URL: https://www.amazon.sg/Physics-Book-Ideas-Simply-Explained/dp/0241412722/ref=sr_1_30?tag=thereadingglo-22
    Username: ''
    Color: '#B3878C'
    Icon-Class: fas fa-book

  - Name: Brief Answers to the Big Questions the final bo...
    URL: https://www.amazon.sg/Brief-Answers-Big-Questions-Stephen/dp/1473695996/ref=sr_1_31?tag=thereadingglo-22
    Username: ''
    Color: '#04EE2E'
    Icon-Class: fas fa-book

  - Name: Science Puzzles for Clever Kids¬Æ Over 100 STEM ...
    URL: https://www.amazon.sg/Science-Puzzles-Clever-Kids%C2%AE-Exercise/dp/1780556632/ref=sr_1_32?tag=thereadingglo-22
    Username: ''
    Color: '#0B602B'
    Icon-Class: fas fa-book

  - Name: Right Kind of Wrong The Science of Failing Well
    URL: https://www.amazon.sg/Right-Kind-Wrong-Science-Failing/dp/1668034573/ref=sr_1_33?tag=thereadingglo-22
    Username: ''
    Color: '#3F3146'
    Icon-Class: fas fa-book

  - Name: The Chemistry Book Big Ideas Simply Explained
    URL: https://www.amazon.sg/Chemistry-Book-Ideas-Simply-Explained/dp/0241515548/ref=sr_1_34?tag=thereadingglo-22
    Username: ''
    Color: '#BC868B'
    Icon-Class: fas fa-book

  - Name: Rehab Science The Complete Guide to Overcoming ...
    URL: https://www.amazon.sg/Rehab-Science-Overcoming-Increasing-MovementThe/dp/1628601396/ref=sr_1_35?tag=thereadingglo-22
    Username: ''
    Color: '#AA272E'
    Icon-Class: fas fa-book

  - Name: Natural History The Ultimate Visual Guide to Ev...
    URL: https://www.amazon.sg/Natural-History-Ultimate-Visual-Everything/dp/0744035015/ref=sr_1_36?tag=thereadingglo-22
    Username: ''
    Color: '#6121FA'
    Icon-Class: fas fa-book

  - Name: Cosmic Queries StarTalks Guide to Who We Are, H...
    URL: https://www.amazon.sg/Cosmic-Queries-StarTalks-Guide-Where/dp/1426221770/ref=sr_1_37?tag=thereadingglo-22
    Username: ''
    Color: '#476BD5'
    Icon-Class: fas fa-book

  - Name: Bigger Leaner Stronger The Simple Science of Bu...
    URL: https://www.amazon.sg/Bigger-Leaner-Stronger-Building-Ultimate/dp/1938895304/ref=sr_1_38?tag=thereadingglo-22
    Username: ''
    Color: '#1F4C0A'
    Icon-Class: fas fa-book

  - Name: Super Interesting Facts For Smart Kids 1272 Fun...
    URL: https://www.amazon.sg/Super-Interesting-Facts-Smart-Kids/dp/B0BGGM9SGY/ref=sr_1_39?tag=thereadingglo-22
    Username: ''
    Color: '#45170A'
    Icon-Class: fas fa-book

  - Name: On the Origin of Time Stephen Hawkings Final Th...
    URL: https://www.amazon.sg/Origin-Time-Stephen-Hawkings-Theory/dp/0593128443/ref=sr_1_40?tag=thereadingglo-22
    Username: ''
    Color: '#DAF7E2'
    Icon-Class: fas fa-book

  - Name: Little Kids First Big Book of Science
    URL: https://www.amazon.sg/Little-Kids-First-Book-Science/dp/1426333188/ref=sr_1_41?tag=thereadingglo-22
    Username: ''
    Color: '#563C0D'
    Icon-Class: fas fa-book

  - Name: Mistakes That Worked 40 Familiar Inventions & H...
    URL: https://www.amazon.sg/Mistakes-That-Worked-Familiar-Inventions/dp/0385320434/ref=sr_1_42?tag=thereadingglo-22
    Username: ''
    Color: '#614FC8'
    Icon-Class: fas fa-book

  - Name: Science of Yoga Understand the Anatomy and Phys...
    URL: https://www.amazon.sg/Science-Yoga-Understand-Physiology-Practice/dp/146547935X/ref=sr_1_43?tag=thereadingglo-22
    Username: ''
    Color: '#8549C6'
    Icon-Class: fas fa-book

  - Name: The Biology Book Big Ideas Simply Explained
    URL: https://www.amazon.sg/Biology-Book-Ideas-Simply-Explained/dp/0744027381/ref=sr_1_44?tag=thereadingglo-22
    Username: ''
    Color: '#A601EF'
    Icon-Class: fas fa-book

  - Name: Project Hail Mary A Novel
    URL: https://www.amazon.sg/Project-Hail-Mary-Andy-Weir/dp/0593135229/ref=sr_1_45?tag=thereadingglo-22
    Username: ''
    Color: '#7E9ECE'
    Icon-Class: fas fa-book

  - Name: The Code Breaker Jennifer Doudna, Gene Editing,...
    URL: https://www.amazon.sg/Code-Breaker-Jennifer-Doudna-Editing/dp/1982115858/ref=sr_1_46?tag=thereadingglo-22
    Username: ''
    Color: '#1214E5'
    Icon-Class: fas fa-book

  - Name: How the World Really Works The Science Behind H...
    URL: https://www.amazon.sg/How-World-Really-Works-Science/dp/0593297067/ref=sr_1_47?tag=thereadingglo-22
    Username: ''
    Color: '#931CCB'
    Icon-Class: fas fa-book

  - Name: American Prometheus The Triumph and Tragedy of ...
    URL: https://www.amazon.sg/American-Prometheus-Triumph-Tragedy-Oppenheimer/dp/0375726268/ref=sr_1_48?tag=thereadingglo-22
    Username: ''
    Color: '#0E585D'
    Icon-Class: fas fa-book



 

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
# footer: 'Yes'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

include:
  - "*.js.html"

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown

# Add jekyll-search plugin
plugins:
  - jekyll-search

template: assets/search.html
